# Generated by Django 6.0.2 on 2026-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
