# Generated by Django 5.2 on 2026-05-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_categoria_alter_cliente_id_alter_mesa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Platillo',
        ),
    ]
